/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SearchIndexImport } from './routes/search/index'
import { Route as SalesIndexImport } from './routes/sales/index'
import { Route as RentalIndexImport } from './routes/rental/index'
import { Route as NewsIndexImport } from './routes/news/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as AuthIndexImport } from './routes/auth/index'
import { Route as SalesNewImport } from './routes/sales/new'
import { Route as SalesIdImport } from './routes/sales/$id'
import { Route as RentalIdImport } from './routes/rental/$id'
import { Route as NewsIdImport } from './routes/news/$id'
import { Route as AuthSignUpImport } from './routes/auth/sign-up'
import { Route as AuthSignInImport } from './routes/auth/sign-in'

// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const IndexLazyRoute = IndexLazyImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const SearchIndexRoute = SearchIndexImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRoute,
} as any)

const SalesIndexRoute = SalesIndexImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => rootRoute,
} as any)

const RentalIndexRoute = RentalIndexImport.update({
  id: '/rental/',
  path: '/rental/',
  getParentRoute: () => rootRoute,
} as any)

const NewsIndexRoute = NewsIndexImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRoute,
} as any)

const SalesNewRoute = SalesNewImport.update({
  id: '/sales/new',
  path: '/sales/new',
  getParentRoute: () => rootRoute,
} as any)

const SalesIdRoute = SalesIdImport.update({
  id: '/sales/$id',
  path: '/sales/$id',
  getParentRoute: () => rootRoute,
} as any)

const RentalIdRoute = RentalIdImport.update({
  id: '/rental/$id',
  path: '/rental/$id',
  getParentRoute: () => rootRoute,
} as any)

const NewsIdRoute = NewsIdImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignUpRoute = AuthSignUpImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignInRoute = AuthSignInImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInImport
      parentRoute: typeof rootRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpImport
      parentRoute: typeof rootRoute
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdImport
      parentRoute: typeof rootRoute
    }
    '/rental/$id': {
      id: '/rental/$id'
      path: '/rental/$id'
      fullPath: '/rental/$id'
      preLoaderRoute: typeof RentalIdImport
      parentRoute: typeof rootRoute
    }
    '/sales/$id': {
      id: '/sales/$id'
      path: '/sales/$id'
      fullPath: '/sales/$id'
      preLoaderRoute: typeof SalesIdImport
      parentRoute: typeof rootRoute
    }
    '/sales/new': {
      id: '/sales/new'
      path: '/sales/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewImport
      parentRoute: typeof rootRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsIndexImport
      parentRoute: typeof rootRoute
    }
    '/rental/': {
      id: '/rental/'
      path: '/rental'
      fullPath: '/rental'
      preLoaderRoute: typeof RentalIndexImport
      parentRoute: typeof rootRoute
    }
    '/sales/': {
      id: '/sales/'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesIndexImport
      parentRoute: typeof rootRoute
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/news/$id': typeof NewsIdRoute
  '/rental/$id': typeof RentalIdRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/news': typeof NewsIndexRoute
  '/rental': typeof RentalIndexRoute
  '/sales': typeof SalesIndexRoute
  '/search': typeof SearchIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/news/$id': typeof NewsIdRoute
  '/rental/$id': typeof RentalIdRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/auth': typeof AuthIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/news': typeof NewsIndexRoute
  '/rental': typeof RentalIndexRoute
  '/sales': typeof SalesIndexRoute
  '/search': typeof SearchIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexLazyRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/news/$id': typeof NewsIdRoute
  '/rental/$id': typeof RentalIdRoute
  '/sales/$id': typeof SalesIdRoute
  '/sales/new': typeof SalesNewRoute
  '/auth/': typeof AuthIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/news/': typeof NewsIndexRoute
  '/rental/': typeof RentalIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/search/': typeof SearchIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/news/$id'
    | '/rental/$id'
    | '/sales/$id'
    | '/sales/new'
    | '/auth'
    | '/dashboard'
    | '/news'
    | '/rental'
    | '/sales'
    | '/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/news/$id'
    | '/rental/$id'
    | '/sales/$id'
    | '/sales/new'
    | '/auth'
    | '/dashboard'
    | '/news'
    | '/rental'
    | '/sales'
    | '/search'
  id:
    | '__root__'
    | '/'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/news/$id'
    | '/rental/$id'
    | '/sales/$id'
    | '/sales/new'
    | '/auth/'
    | '/dashboard/'
    | '/news/'
    | '/rental/'
    | '/sales/'
    | '/search/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  NewsIdRoute: typeof NewsIdRoute
  RentalIdRoute: typeof RentalIdRoute
  SalesIdRoute: typeof SalesIdRoute
  SalesNewRoute: typeof SalesNewRoute
  AuthIndexRoute: typeof AuthIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  NewsIndexRoute: typeof NewsIndexRoute
  RentalIndexRoute: typeof RentalIndexRoute
  SalesIndexRoute: typeof SalesIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  NewsIdRoute: NewsIdRoute,
  RentalIdRoute: RentalIdRoute,
  SalesIdRoute: SalesIdRoute,
  SalesNewRoute: SalesNewRoute,
  AuthIndexRoute: AuthIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  NewsIndexRoute: NewsIndexRoute,
  RentalIndexRoute: RentalIndexRoute,
  SalesIndexRoute: SalesIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/sign-in",
        "/auth/sign-up",
        "/news/$id",
        "/rental/$id",
        "/sales/$id",
        "/sales/new",
        "/auth/",
        "/dashboard/",
        "/news/",
        "/rental/",
        "/sales/",
        "/search/"
      ]
    },
    "/": {
      "filePath": "index.lazy.tsx"
    },
    "/auth/sign-in": {
      "filePath": "auth/sign-in.tsx"
    },
    "/auth/sign-up": {
      "filePath": "auth/sign-up.tsx"
    },
    "/news/$id": {
      "filePath": "news/$id.tsx"
    },
    "/rental/$id": {
      "filePath": "rental/$id.tsx"
    },
    "/sales/$id": {
      "filePath": "sales/$id.tsx"
    },
    "/sales/new": {
      "filePath": "sales/new.tsx"
    },
    "/auth/": {
      "filePath": "auth/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/news/": {
      "filePath": "news/index.tsx"
    },
    "/rental/": {
      "filePath": "rental/index.tsx"
    },
    "/sales/": {
      "filePath": "sales/index.tsx"
    },
    "/search/": {
      "filePath": "search/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
